import os
import json
import smtplib
import requests
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from strands import tool
from db.schema import get_session, DigestLog, AttentionItem


@tool
def format_digest(
    experiment_name: str,
    leaderboard: list,
    summary: dict,
    trend: str,
    regression: bool,
    nl_interpretation: str,
    runs_completed_today: int = 0,
    runs_failed_today: int = 0
) -> dict:
    """Format all analysis data into a clean markdown digest."""
    now   = datetime.now()
    date  = now.strftime("%B %d, %Y")
    lines = []

    lines.append(f"# ExperimentMind Daily Digest — {date}")
    lines.append(f"**Experiment:** {experiment_name}\n")

    lines.append(f"## Summary")
    lines.append(f"- ✅ Runs completed today: **{runs_completed_today}**")
    lines.append(f"- ❌ Runs failed today: **{runs_failed_today}**")
    lines.append(f"- 📊 Total runs to date: **{summary.get('total_runs', 0)}**")
    lines.append(f"- 📈 Trend: **{trend.upper()}**")
    if regression:
        lines.append(f"- ⚠️ **REGRESSION DETECTED** — performance declining\n")
    else:
        lines.append("")

    lines.append(f"## Leaderboard ({summary.get('primary_metric', 'val_accuracy')})")
    lines.append(f"| Rank | Run | Score | Delta |")
    lines.append(f"|------|-----|-------|-------|")
    for entry in leaderboard[:5]:
        medal = "🥇" if entry["is_best"] else f"#{entry['rank']}"
        run_short = entry["run_id"][-30:]
        lines.append(
            f"| {medal} | `{run_short}` | "
            f"**{entry['metric_value']}** | "
            f"{entry['delta_vs_best']:+.4f} |"
        )

    lines.append(f"\n## Best Model")
    lines.append(f"- **Run ID:** `{leaderboard[0]['run_id']}`")
    lines.append(f"- **Score:** {leaderboard[0]['metric_value']}")
    lines.append(f"- **Baseline:** {summary.get('baseline_value')}")
    lines.append(f"- **Total improvement:** +{summary.get('improvement_pct')}%\n")

    lines.append(f"## Analysis")
    lines.append(nl_interpretation)

    lines.append(f"\n---")
    lines.append(f"*Generated by ExperimentMind at {now.strftime('%H:%M:%S')}*")

    content = "\n".join(lines)
    return {"success": True, "content": content, "date": date}


@tool
def save_digest(content: str, date: str) -> dict:
    """Save digest to the digests/ folder and log to database."""
    try:
        os.makedirs("digests", exist_ok=True)
        filename = f"digests/digest_{date.replace(' ', '_').replace(',', '')}.md"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)

        session = get_session()
        log = DigestLog(
            digest_date    = date,
            content_md     = content,
            runs_completed = 0,
            runs_failed    = 0,
            new_best       = False
        )
        session.add(log)
        session.commit()
        session.close()

        return {"success": True, "path": filename,
                "message": f"Digest saved to {filename}"}
    except Exception as e:
        return {"success": False, "error": str(e)}


@tool
def send_email_digest(content: str, subject: str) -> dict:
    """Send the digest via email using SMTP credentials from .env"""
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    to_email  = os.getenv("DIGEST_EMAIL_TO")

    if not all([smtp_host, smtp_user, smtp_pass, to_email]):
        return {
            "success": False,
            "skipped": True,
            "reason": "Email not configured in .env — digest saved to file only"
        }

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = smtp_user
        msg["To"]      = to_email

        html = content\
            .replace("# ", "<h1>")\
            .replace("## ", "<h2>")\
            .replace("**", "<strong>")\
            .replace("\n", "<br>")

        msg.attach(MIMEText(content, "plain"))
        msg.attach(MIMEText(html, "html"))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, to_email, msg.as_string())

        return {"success": True, "sent_to": to_email, "subject": subject}
    except Exception as e:
        return {"success": False, "error": str(e)}


@tool
def send_slack_digest(content: str, subject: str) -> dict:
    """Send digest summary to Slack via webhook."""
    webhook_url = os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        return {"success": False, "skipped": True,
                "reason": "SLACK_WEBHOOK_URL not set in .env"}

    try:
        # Send first 2000 chars to Slack (Slack message limit)
        short = content[:2000] + "..." if len(content) > 2000 else content
        payload = {"text": f"*{subject}*\n\n{short}"}
        response = requests.post(webhook_url, json=payload, timeout=10)

        if response.status_code == 200:
            return {"success": True, "message": "Slack notification sent"}
        return {"success": False, "error": f"Slack returned {response.status_code}"}
    except Exception as e:
        return {"success": False, "error": str(e)}


@tool
def add_attention_item(item_type: str, run_id: str,
                       title: str, description: str) -> dict:
    """Add an item to the attention queue for human review."""
    try:
        session = get_session()
        item = AttentionItem(
            item_type   = item_type,
            run_id      = run_id,
            title       = title,
            description = description,
            resolved    = False
        )
        session.add(item)
        session.commit()
        session.close()
        return {"success": True, "message": f"Attention item added: {title}"}
    except Exception as e:
        return {"success": False, "error": str(e)}


@tool
def get_attention_items() -> dict:
    """Get all unresolved attention items from the queue."""
    try:
        session = get_session()
        items = session.query(AttentionItem)\
                       .filter(AttentionItem.resolved == False)\
                       .order_by(AttentionItem.created_at.desc())\
                       .all()
        result = [{
            "id":          item.id,
            "type":        item.item_type,
            "run_id":      item.run_id,
            "title":       item.title,
            "description": item.description,
            "created_at":  item.created_at.isoformat() if item.created_at else None
        } for item in items]
        session.close()
        return {"success": True, "count": len(result), "items": result}
    except Exception as e:
        return {"success": False, "error": str(e)}